model:
  engine_path: "weights/yolov8n.engine"
  confidence_threshold: 0.30

openwebcamdb:
  api_key: "197|URDz8nUJ65Lhm5lWnRl67UVNKj4qEDQiQFhOJWT65f179f5e"
  limit: 2

analytics:
  target_colors: ["red", "blue", "green"]

ffmpeg_path: "ffmpeg"