analytics:
  target_colors: ["red", "blue", "green", "black", "white"]

ffmpeg_path: "ffmpeg"

cameras:
  - id: 1
    name: "Jackson Hole Town Square"
    rtsp_url: "https://www.youtube.com/watch?v=gFRtAAmiFbE"
    line_zone: [[0, 360], [1280, 360]] 
    
  - id: 2
    name: "Live Traffic Feed"
    rtsp_url: "https://www.youtube.com/watch?v=DjdUEyjx8GM"
    line_zone: [[0, 360], [1280, 360]]

  - id: 3
    name: "Dublin- Ireland"
    rtsp_url: "https://www.youtube.com/live/3nyPER2kzqk?si=EnQu2nMpQttkiMtr"
    line_zone: [[0, 360], [1280, 360]]

  - id: 4
    name: "Davao City"
    rtsp_url: "https://www.youtube.com/live/UJxvgeRnuUQ?si=HVZrJlPGuQ2uOQnS"
    line_zone: [[0, 360], [1280, 360]]

  